default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: wzyzcz
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ForumApp_development

test:
  <<: *default
  database: ForumApp_test

production:
  <<: *default
  database: ForumApp_production
  username: ForumApp
  password: <%= ENV['FORUMAPP_DATABASE_PASSWORD'] %>
